---

- name: Update all packages to the latest version
  become: true
  apt:
    update_cache: yes
    upgrade: dist
- name: install apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - git
      - libjpeg-dev
      - libpq-dev
      - nginx
      - postgresql
      - python-dev
      - python-psycopg2
      - python-setuptools
      - supervisor
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - libffi-dev
      - libssl-dev
      - python3
      - python3-dev
      - python3-pip
      - python-pip
      


- include: crawl_and_api.yml

- include: web.yml
  tags: [terria]
- include: nginx.yml
  tags: [nginx]