---
# - name: bring up web interface and crawler
  # vars_files:
  #   - secrets.yml
  # tasks:
  #   - name: Update all packages to the latest version
  #     become: true
  #     apt:
  #       upgrade: dist
  #   - name: install apt packages
  #     become: true
  #     apt:
  #       update_cache: yes
  #       cache_valid_time: 3600
  #       pkg:
  #         - git
  #         - libjpeg-dev
  #         - libpq-dev
  #         - nginx
  #         - postgresql
  #         - python-dev
  #         - python-psycopg2
  #         - python-setuptools
  #         - supervisor
  #         - libxml2-dev
  #         - libxslt1-dev
  #         - zlib1g-dev
  #         - libffi-dev
  #         - libssl-dev
  #         - python3
  #         - python3-dev
  #         - python3-pip
  #         - nodejs
  #         - npm
  #         - yarn
  #   - name: clone the repo
  #     git: repo={{ repo_url }} dest={{ proj_path }} accept_hostkey=yes

  #   - name: install requirements.txt
  #     pip:
  #       requirements: "{{ proj_path }}/{{ reqs_path }}"
  #       executable: pip3
  #       extra_args: --user
  #   - name: Create a user systemd folder if it does not exist
  #     file:
  #       path: "{{ user_systemd_path }}"
  #       state: directory
  #       mode: "0755"
  #   - name: install crawl systemd unit file
  #     template: src=templates/aqi_crawl.service.j2 dest={{ user_systemd_path }}/aqi_crawl.service
  #   - name: install crawl systemd timer file
  #     template: src=templates/aqi_crawl.timer.j2 dest={{ user_systemd_path }}/aqi_crawl.timer
  #   - name: copy config file
  #     template: src=templates/config.py.j2 dest={{ proj_path }}/config.py

  #   - name: Change the working directory to migrate db
  #     shell: python3 manage.py db init
  #     ignore_errors: yes
  #     args:
  #       chdir: "{{ proj_path }}"
  #   - name: migrate db
  #     shell: python3 manage.py db migrate
  #     ignore_errors: yes
  #     args:
  #       chdir: "{{ proj_path }}"
  #   - name: upgrade db
  #     shell: python3 manage.py db upgrade
  #     ignore_errors: yes
  #     args:
  #       chdir: "{{ proj_path }}"
  #   - name: enable lingering for user systemd task
  #     shell: loginctl enable-linger {{ user }}
  #     become: yes

  #   # not sure if it's useful, if not, reboot works.
  #   - name: reload systemd daemon
  #     systemd:
  #       daemon_reload: yes
  #     become: yes
  #   - name: start crawl service
  #     systemd:
  #       name: aqi_crawl.service
  #       enabled: yes
  #       state: started
  #       scope: user

  #   - name: enable a timer for aqi_crawl
  #     systemd:
  #       name: aqi_crawl.timer
  #       enabled: yes
  #       state: started
  #       scope: user
  #       daemon_reload: yes

  #   - name: set the gunicorn config file
  #     template: src=gunicorn.conf.py.j2 dest={{ proj_path }}/gunicorn.conf.py
  #   - name: set the supervisor config file
  #     template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/aqi.conf
  #     become: True
  #     notify: restart supervisor
