---
- name: gather the missing facts.., not sure why facts not gathered when running with this tag
  gather_facts:
  
- name: set the gunicorn config file
  template: src=templates/gunicorn.conf.py.j2 dest={{ proj_path }}/gunicorn.conf.py
- name: set the supervisor config file
  template: src=templates/supervisor.conf.j2 dest=/etc/supervisor/conf.d/{{ proj_name }}.conf
  become: True
- name: restart supervisor
  supervisorctl: "name={{ gunicorn_procname }} state=restarted"
  become: True

- name: set the nginx config file
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/map.conf
  notify: restart nginx
  become: True
- name: enable the nginx config file
  file:
    src: /etc/nginx/sites-available/map.conf
    dest: /etc/nginx/sites-enabled/map.conf
    state: link
  notify: restart nginx
  become: True
- name: remove the default nginx config file
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
  become: True
